Application: &ApplicationDefaults
  Organizations:

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer.fte.com:7050
  BatchTimeout: 5s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Organizations:

- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererOrg
  MSPDir: crypto-config/ordererOrganizations/fte.com/msp

- &Org1
  Name: Org1FTE
  ID: Org1FTE
  MSPDir: crypto-config/peerOrganizations/app.fte.com/msp
  AnchorPeers:
  - Host: peer0.app.fte.com
    Port: 7051

- &Org2
  Name: Org2BNK
  ID: Org2BNK
  MSPDir: crypto-config/peerOrganizations/bank.com/msp
  AnchorPeers:
  - Host: peer0.bank.com
    Port: 7051

- &Org3
  Name: Org3SHP
  ID: Org3SHP
  MSPDir: crypto-config/peerOrganizations/ship.com/msp
  AnchorPeers:
  - Host: peer0.ship.com
    Port: 7051

Profiles:

  TradeFinanceOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg

    Consortiums:
      TradeConsortium:
        Organizations:
        - *Org1
        - *Org2
        - *Org3
  
  TradeFinanceOrgsChannel:
    Consortium: TradeConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
