version: '2'

networks: 
  tradenetwork:

services:

  orderer.fte.com:
    extends:
      file: base/base.yaml
      service: orderer.fte.com
    container_name: orderer.fte.com
    networks:
    - tradenetwork

  peer0.app.fte.com:
    extends:
      file: base/base.yaml
      service: peer0.app.fte.com
    container_name: peer0.app.fte.com
    networks:
    - tradenetwork

  peer1.app.fte.com:
    extends:
      file: base/base.yaml
      service: peer1.app.fte.com
    container_name: peer1.app.fte.com
    networks:
    - tradenetwork

  peer0.bank.com:
    extends:
      file: base/base.yaml
      service: peer0.bank.com
    container_name: peer0.bank.com
    networks:
    - tradenetwork

  peer1.bank.com:
    extends:
      file: base/base.yaml
      service: peer1.bank.com
    container_name: peer1.bank.com
    networks:
    - tradenetwork

  peer0.ship.com:
    extends:
      file: base/base.yaml
      service: peer0.ship.com
    container_name: peer0.ship.com
    networks:
    - tradenetwork

  peer1.ship.com:
    extends:
      file: base/base.yaml
      service: peer1.ship.com
    container_name: peer1.ship.com
    networks:
    - tradenetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.app.fte.com:7052
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.app.fte.com:7051
      - CORE_PEER_LOCALMSPID=Org1FTE
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/app.fte.com/peers/peer0.app.fte.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/app.fte.com/peers/peer0.app.fte.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/app.fte.com/peers/peer0.app.fte.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/app.fte.com/users/Admin@app.fte.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.fte.com
      - peer0.app.fte.com
      - peer1.app.fte.com
      - peer0.bank.com
      - peer1.bank.com
      - peer0.ship.com
      - peer1.ship.com
    networks:
    - tradenetwork